name: revel_ui
description: RevelUi UI library
version: 0.0.1

environment: 
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  google_fonts: ^3.0.1
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.1.4

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/pearl.svg
    - assets/images/lucas.png
    - assets/images/babies.png
    - assets/images/im_a_boy.png
    - assets/images/pearl_boy.svg
    - assets/images/little_boy.png
    - assets/images/pearl_girl.svg
    - assets/images/line_diagonal.svg
    - assets/images/line_vertical.svg
    - assets/images/line_horizontal.svg

flutter_gen:
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true